// Code generated by MockGen. DO NOT EDIT.
// Source: ./interfaces/gin_helper.go
//
// Generated by this command:
//
//	mockgen -source=./interfaces/gin_helper.go -destination=./mocks/gin_helper.go -package=mocks
//
// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "go.uber.org/mock/gomock"
)

// MockIGinHelper is a mock of IGinHelper interface.
type MockIGinHelper[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockIGinHelperMockRecorder[T]
}

// MockIGinHelperMockRecorder is the mock recorder for MockIGinHelper.
type MockIGinHelperMockRecorder[T any] struct {
	mock *MockIGinHelper[T]
}

// NewMockIGinHelper creates a new mock instance.
func NewMockIGinHelper[T any](ctrl *gomock.Controller) *MockIGinHelper[T] {
	mock := &MockIGinHelper[T]{ctrl: ctrl}
	mock.recorder = &MockIGinHelperMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIGinHelper[T]) EXPECT() *MockIGinHelperMockRecorder[T] {
	return m.recorder
}
